name: CI/CD Pipeline with SonarQube, Trivy, and Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # ✅ Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # ✅ Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # ✅ Instalar dependências corretamente (Flask, pytest, etc.)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ✅ Configurar PYTHONPATH
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV

      # ✅ Rodar testes com cobertura mínima de 80%
      - name: Run tests
        run: pytest tests/ --cov=src --cov-fail-under=80 --cov-report=xml:coverage.xml

      # ✅ Executar Análise do SonarQube
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.organization=agner \
            -Dsonar.projectKey=agner_venhaparaoleds-devops \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io

      # ✅ Construir a imagem Docker
      - name: Build Docker image
        run: docker build -t concurso-publico .

      # ✅ Instalar Trivy (scanner de segurança)
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # ✅ Escanear a imagem Docker com Trivy
      - name: Scan Docker image with Trivy
        run: trivy image --severity HIGH,CRITICAL concurso-publico

      # ✅ Login no GitHub Packages (se for um push na `main`)
      - name: Login to GitHub Packages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # ✅ Publicar imagem no GitHub Container Registry (apenas para push)
      - name: Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag concurso-publico ghcr.io/agnerloss/venhaparaoleds-devops/concurso-publico:latest
          docker tag concurso-publico ghcr.io/agnerloss/venhaparaoleds-devops/concurso-publico:${{ github.sha }}
          docker push ghcr.io/agnerloss/venhaparaoleds-devops/concurso-publico:latest
          docker push ghcr.io/agnerloss/venhaparaoleds-devops/concurso-publico:${{ github.sha }}

      # ✅ Limpeza do workspace
      - name: Clean up workspace
        if: always()
        run: rm -rf $HOME/sonar-scanner-7.0.2.4839-linux-x64 sonar-scanner.zip

  provision-infrastructure:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      # ✅ Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # ✅ Configurar Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      # ✅ Inicializar Terraform
      - name: Terraform Init
        run: terraform init

      # ✅ Aplicar mudanças no Terraform (infraestrutura)
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="ghcr_token=${{ secrets.GHCR_TOKEN }}" 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
