name: CI/CD Pipeline with SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Verifica o código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Passo 2: Configura o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Passo 3: Instala dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      # Passo 4: Instalar SonarScanner (usando a versão 7.0.2.4839)
      - name: Download and Install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.0.2.4839-linux-x64.zip
          unzip sonar-scanner.zip -d $HOME
          export PATH=$HOME/sonar-scanner-7.0.2.4839-linux-x64/bin:$PATH

      # Passo 5: Rodar os testes
      - name: Run tests
        run: |
          pytest tests/ --cov=src --cov-fail-under=80

      # Passo 6: Executar Análise do SonarQube
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=concurso-publico \
            -Dsonar.sources=src \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

      # Passo 7: Construir a imagem Docker
      - name: Build Docker image
        run: docker build -t concurso-publico .

      # Passo 8: Login no GitHub Packages (apenas para push)
      - name: Login to GitHub Packages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Passo 9: Push para o GitHub Container Registry (apenas para push)
      - name: Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag concurso-publico ghcr.io/${{ github.repository }}/concurso-publico:latest
          docker push ghcr.io/${{ github.repository }}/concurso-publico:latest
